# Generated by Django 2.1a1 on 2019-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='dob',
            field=models.CharField(max_length=30),
        ),
    ]
