# Generated by Django 2.1a1 on 2019-03-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190315_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='dob',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
